# --- Dependency Values ---
ingress-nginx:
  enabled: false
  controller:
    service:
      annotations:
        # This is to make AKS work. I am open to better options.
        service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz

cert-manager:
  enabled: false

# --- XDM Values ---
xdm_version: latest
xdm_active_image: semarchy/xdm:{{ .Values.xdm_version }}
xdm_passive_image: semarchy/xdm:{{ .Values.xdm_version }}-passive

# NodePort Values
xdm_active_service_nodeport: 30000
xdm_passive_service_nodeport: 30001

# DNS Configuration
active_host_name: xdma.yourdomain.com
passive_host_name: xdm.yourdomain.com

# Cert Manager Configuration
# -- ACME Staging ---
#acme_server_url: https://acme-staging-v02.api.letsencrypt.org/directory
# -- ACME Prod ---
acme_server_url: https://acme-v02.api.letsencrypt.org/directory
acme_registration_email: thomas.wyrick@semarchy.com

# Pod Configurations
active_mem_requests: 4Gi
active_mem_limits: 5Gi

passive_node_replicas: 2
passive_mem_requests: 2Gi
passive_mem_limits: 3Gi

# This is a one-time value used when provisioning the cluster
semarchy_setup_token: mySecretToken

# Database Users and Configuration
# -- PostgreSQL --
xdm_repository_driver: org.postgresql.Driver
xdm_repository_url: jdbc:postgresql://<cluster-ip-address>:<cluster-port>/semarchy_repository
# -- SQL Server --
#xdm_repository_driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
#xdm_repository_url: jdbc:sqlserver://localhost:1433;databaseName=REPOSITORY
# -- Oracle Database --
#xdm_repository_driver: oracle.jdbc.OracleDriver
#xdm_repository_url: jdbc:oracle:thin:@localhost:1521:XE
#xdm_repository_ro_cnxn_init_sql: ALTER SESSION SET CURRENT_SCHEMA = repository_user

xdm_repository_username: semarchy_repository
xdm_repository_password: semarchy_repository
xdm_repository_ro_username: semarchy_repository_ro
xdm_repository_ro_password: semarchy_repository_ro
