apiVersion: apps/v1
kind: Deployment
metadata:
  name: semarchy-appserver-passive
  labels:
    app: semarchy-appserver-passive
spec:
  replicas: {{.Values.passive_node_replicas}}
  selector:
    matchLabels:
      app: semarchy-appserver-passive
  template:
    metadata:
      labels:
        app: semarchy-appserver-passive
    spec:
      containers:
        - name: semarchy-appserver-passive
          image: {{tpl .Values.xdm_passive_image .}}
          resources:
            requests:
              memory: "{{.Values.passive_mem_requests}}"
            limits:
              memory: "{{.Values.passive_mem_limits}}"
          envFrom:
            - configMapRef:
                name: xdm-configmap
          envFrom:
            - secretRef:
                name: xdm-secrets
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /semarchy/api/rest/probes/started
              port: 8080
            failureThreshold: 10
            periodSeconds: 10
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: semarchy-appserver-passive
  labels:
    app: semarchy-appserver-passive
spec:
  ports:
    - port: 8080
  selector:
    app: semarchy-appserver-passive
