apiVersion: apps/v1
kind: Deployment
metadata:
  name: semarchy-appserver-active
  labels:
    app: semarchy-appserver-active
spec:
  replicas: 1
  selector:
    matchLabels:
      app: semarchy-appserver-active
  template:
    metadata:
      labels:
        app: semarchy-appserver-active
    spec:
      containers:
        - name: semarchy-appserver-active
          image: {{tpl .Values.xdm_active_image .}}
          resources:
            requests:
              memory: "{{ .Values.active_mem_requests }}"
            limits:
              memory: "{{ .Values.active_mem_limits }}"
          envFrom:
            - configMapRef:
                name: xdm-configmap
            - secretRef:
                name: xdm-secrets
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /semarchy/api/rest/probes/started
              port: 8080
            failureThreshold: 10
            periodSeconds: 10
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: semarchy-appserver-active
  labels:
    app: semarchy-appserver-active
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app: semarchy-appserver-active
