apiVersion: apps/v1
kind: Deployment
metadata:
  name: semarchy-appserver-passive
  labels:
    app: semarchy-appserver-passive
spec:
  replicas: {{.Values.passive_node_replicas}}
  selector:
    matchLabels:
      app: semarchy-appserver-passive
  template:
    metadata:
      labels:
        app: semarchy-appserver-passive
    spec:
      containers:
        - image: {{tpl .Values.xdm_passive_image .}}
          name: semarchy-appserver-passive
          resources:
            requests:
              memory: "{{.Values.passive_mem_requests}}"
            limits:
              memory: "{{.Values.passive_mem_limits}}"
          envFrom:
            - configMapRef:
                name: xdm-configmap
          env:
            - name: SEMARCHY_SETUP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: xdm-secrets
                  key: semarchy_setup_token
            - name: XDM_REPOSITORY_URL
              valueFrom:
                secretKeyRef:
                  name: xdm-secrets
                  key: xdm_repository_url
            - name: XDM_REPOSITORY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: xdm-secrets
                  key: xdm_repository_username
            - name: XDM_REPOSITORY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: xdm-secrets
                  key: xdm_repository_password
            - name: XDM_REPOSITORY_READONLY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: xdm-secrets
                  key: xdm_repository_ro_username
            - name: XDM_REPOSITORY_READONLY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: xdm-secrets
                  key: xdm_repository_ro_password
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /semarchy/api/rest/probes/started
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: semarchy-appserver-passive
  labels:
    app: semarchy-appserver-passive
spec:
  ports:
    - port: 8080
  selector:
    app: semarchy-appserver-passive
