apiVersion: apps/v1
kind: Deployment
metadata:
  name: semarchy-appserver-active
  labels:
    app: semarchy-appserver-active
spec:
  replicas: 1
  selector:
    matchLabels:
      app: semarchy-appserver-active
  template:
    metadata:
      labels:
        app: semarchy-appserver-active
    spec:
      containers:
        - name: semarchy-appserver-active
          image: {{tpl .Values.xdm_active_image .}}
          resources:
            requests:
              memory: "{{ .Values.active_mem_requests }}"
            limits:
              memory: "{{ .Values.active_mem_limits }}"
          volumeMounts:
            - mountPath: /usr/local/tomcat/logs
              name: logs
          envFrom:
            - configMapRef:
                name: xdm-configmap
          envFrom:
            - secretRef:
                name: xdm-secrets
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /semarchy/api/rest/probes/started
              port: 8080
            failureThreshold: 10
            periodSeconds: 10
        - name: logging-sidecar
          image: busybox:1.28
          args: [/bin/sh, -c, 'tail -n+1 -F /usr/local/tomcat/logs/semarchy.log']
          volumeMounts:
            - name: logs
              mountPath: /usr/local/tomcat/logs
      volumes:
        - name: logs
          emptyDir: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: semarchy-appserver-active
  labels:
    app: semarchy-appserver-active
spec:
  ports:
    - port: 8080
  selector:
    app: semarchy-appserver-active
