apiVersion: v1
kind: Secret
metadata:
  name: xdm-secrets
type: Opaque
stringData:
  semarchy_setup_token: mySecretToken
  xdm_repository_url: jdbc:postgresql://host.minikube.internal:5432/postgres
  xdm_repository_username: semarchy_repository
  xdm_repository_password: semarchy_repository
  xdm_repository_ro_username: semarchy_repository_ro
  xdm_repository_ro_password: semarchy_repository_ro
