apiVersion: v1
kind: Secret
metadata:
    name: xdm-secrets
type: Opaque
stringData:
    SEMARCHY_SETUP_TOKEN: {{ .Values.semarchy_setup_token }}
    
    XDM_REPOSITORY_DRIVER: {{ .Values.xdm_repository_driver }}
    XDM_REPOSITORY_URL: {{ .Values.xdm_repository_url }}
    
    XDM_REPOSITORY_USERNAME: {{ .Values.xdm_repository_username }}
    XDM_REPOSITORY_PASSWORD: {{ .Values.xdm_repository_password }}
    XDM_REPOSITORY_READONLY_USERNAME: {{ .Values.xdm_repository_ro_username }}
    XDM_REPOSITORY_READONLY_PASSWORD: {{ .Values.xdm_repository_ro_password }}
